#!/bin/bash

if ! hash "docker-compose"; then
  echo "Installing docker-compose"
  pip install docker-compose
else
  echo "docker-compose already installed"
fi

if ! type "z" > /dev/null; then
  echo "Installing z"
  if [ ! -d ~/code ]; then
    mkdir -p ~/code
    chown ${USER}:${USER} ~/code
  fi

  cd ~/code && git clone https://github.com/rupa/z.git
  chown ${USER}:${USER} ~/code/z

  echo "source ~/code/z/z.sh" >> ~/.bashrc
else
  echo "z already installed"
fi
