#!/bin/bash

if ! hash "docker-compose"; then
  echo "Installing docker-compose"
  sudo pip install docker-compose
else
  echo "docker-compose already installed"
fi

if ! type "z" > /dev/null; then
  echo "Installing z"
  mkdir -p ~/code
  cd ~/code && git clone https://github.com/rupa/z.git
  echo "source ~/code/z.sh" >> ~/.bash_rc
else
  echo "z already installed"
fi
